### ISSUE TITLE
Uploading NFTs (mp4) into a new collection gets stuck

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/app#41]
Hi devs,

A user reported on discord that initially uploading mp4 files into a new NFT collection gets stuck while processing the CSV (bugissue-373)

Original message:
_hi, i can t list more than ~30-40 nft (mp4 /17mb each) . either i get a wrong csv file (only 20 nft are in the list, sometimes 10, 30,...)  or it stucks (mostly with the last file ).  png works fine_

Greetings,
Bananu

**Comment by adamunchained** [comment]
Can you please provide steps to reproduce?

**Comment by gitoess** [comment]
hi, 
create an stf collection ("interactive" )  and go to "multiple" . than load a bunch of mp4 (bigger than 10-15mb).  10-20nft should be fine. 50nft with some issues by time and 99 with most likely more than 1 issue:

issues:
1: e.g 99 nft but stucks loading at 98 
2: got wrong csv file (10 instead of 99 positions)
3: "download csv" button disappears after few seconds
4: whole uploaded nft disappears

i tried it about 20+times.
 finally i managed it with 99nft a 3.6mb.  (failed with: 99mb, 18mb, 8mb.)
