### ISSUE TITLE
Allow discord and other social media tags to be hidden

### ISSUE THREAD

**Issue by iotaflea** [soonaverse/app#70]
Many discord bots and verification methods utilized by projects require discord or social media profiles to be added to soonaverse profiles.  This intrudes on privacy for some and can also expose unnecessary information about the account to nefarious actors.  It would be nice if you could upload that information but check a box that it is not displayed publicly or even better, allow those functions where it's needed such as discord verification to occur but is unavailable to pull from the profile.

**Comment by adamunchained** [comment]
As per Taskforce request, adding some comments based on what I think the issue is: 

- I think this needs more research and agreed by TF what to do. How will this work since we're talking about public ledger? How do you intend to store their profile on Tangle in the future? Are you talking about hidding just on UI but it can still be retrieved via API?
