### ISSUE TITLE
NFT Launchpad

### ISSUE THREAD

**Issue by DiePutze5853** [soonaverse/app#85]
The NFT Launchpad should give artists and spaces the option to release an NFT collection without having to pay up front for the storage deposit, similar to crowdfunding campaigns. 
If the revenue of the NFT Launchpad sale reaches the threshold to cover the required storage deposit for the whole collection it will be minted automatically on either on the Shimmer or Iota network. 
The Launchpad sale should only be open for a predetermined timeframe. If the collection revenues within the timeframe are not enough to cover the minting costs users will be reimbursed automatically.

**Comment by adamunchained** [comment]
As per Taskforce request, adding some comments based on what I think the issue is: 

- how do you define the revenue? 100% of the sale of NFT? or just royalties? or %? Is this supposed to be automatic and set aside for a separate wallet? 
- sounds cool, I think it needs to be flashed out more and B5 can assist building function for it if required and prioritized by TF
